/**
 * Represents a product with its core attributes.
 */
export interface Product {
  /**
   * The unique identifier for the product.
   */
  id: string;
  /**
   * The name of the product.
   */
  name: string;
  /**
   * Relevant sales data for the product.
   */
  salesData: SalesData;
}

/**
 * Represents sales data for a product.
 */
export interface SalesData {
  /**
   * The number of units sold.
   */
  unitsSold: number;
  /**
   * The revenue generated by the product.
   */
  revenue: number;
}

// Mock data store
let mockProducts: Product[] = [
  { id: 'P001', name: 'Quantum Laptop X', salesData: { unitsSold: 150, revenue: 180000 } },
  { id: 'P002', name: 'Nebula Smartphone Z', salesData: { unitsSold: 450, revenue: 315000 } },
  { id: 'P003', name: 'Aether Tablet Pro', salesData: { unitsSold: 280, revenue: 140000 } },
  { id: 'P004', name: 'Cosmos Smartwatch', salesData: { unitsSold: 620, revenue: 155000 } },
  { id: 'P005', name: 'Orion Wireless Buds', salesData: { unitsSold: 850, revenue: 85000 } },
  { id: 'P006', name: 'Galaxy VR Headset', salesData: { unitsSold: 95, revenue: 47500 } },
  { id: 'P007', name: 'Nova Gaming Console', salesData: { unitsSold: 180, revenue: 90000 } },
  { id: 'P008', name: 'Starlight E-reader', salesData: { unitsSold: 310, revenue: 31000 } },
  { id: 'P009', name: 'Pulsar Drone MK.II', salesData: { unitsSold: 50, revenue: 75000 } },
  { id: 'P010', name: 'Eclipse Bluetooth Speaker', salesData: { unitsSold: 500, revenue: 25000 } },
];

// Simulate API delay
const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

/**
 * Asynchronously retrieves a list of products.
 * @returns A promise that resolves to an array of Product objects.
 */
export async function getProducts(): Promise<Product[]> {
  await delay(50); // Simulate network latency
  // Return a copy to prevent direct mutation of the mock data store
  return [...mockProducts];
}

/**
 * Asynchronously retrieves a product by its ID.
 * @param id The ID of the product to retrieve.
 * @returns A promise that resolves to a Product object or null if not found.
 */
export async function getProduct(id: string): Promise<Product | null> {
  await delay(30);
  const product = mockProducts.find(p => p.id === id);
  return product ? { ...product } : null; // Return a copy
}

/**
 * Asynchronously adds a new product.
 * @param productData Data for the new product (without ID).
 * @returns A promise that resolves to the added Product object.
 */
export async function addProduct(productData: Omit<Product, 'id'>): Promise<Product> {
  await delay(80);
  const newId = `P${String(Date.now()).slice(-4)}`; // Simple mock ID generation
  const newProduct: Product = {
    ...productData,
    id: newId,
  };
  mockProducts.push(newProduct);
  return { ...newProduct }; // Return a copy
}

/**
 * Asynchronously updates an existing product.
 * @param id The ID of the product to update.
 * @param updatedData The updated product data.
 * @returns A promise that resolves to the updated Product object or null if not found.
 */
export async function updateProduct(id: string, updatedData: Omit<Product, 'id'>): Promise<Product | null> {
    await delay(70);
    const productIndex = mockProducts.findIndex(p => p.id === id);
    if (productIndex === -1) {
        return null;
    }
    const updatedProduct = { ...mockProducts[productIndex], ...updatedData };
    mockProducts[productIndex] = updatedProduct;
    return { ...updatedProduct }; // Return a copy
}


/**
 * Asynchronously deletes a product.
 * @param id The ID of the product to delete.
 * @returns A promise that resolves to true if deletion was successful, false otherwise.
 */
export async function deleteProduct(id: string): Promise<boolean> {
  await delay(60);
  const initialLength = mockProducts.length;
  mockProducts = mockProducts.filter(p => p.id !== id);
  return mockProducts.length < initialLength;
}
